### ISSUE TITLE
Deleting image not working properly

### ISSUE THREAD

**Issue by ralucac-telenav** [kartaview/openstreetcam.org#10]
Issue #1:
When deleting an imagine, nothing happens: there is no confirmation that the action happened and the "Delete Photo/Are you sure you want to delete this photo?" popup does not disappear. But after refresh the image is deleted, it's just that the user does not know immediately that it happened. 

Issue #2: 
Deleting multiple imagines in sequence does not seem to work (so going with next through each image and deleting it). The only way that it seems to work is: delete one image, refresh the page, delete another image, refresh and so on.

Issue #3:
When deleting the first image of a track, the "my tracks" view where the tracks are listed, does no display the next image as the first imagine in the track, but rather a "not found" placeholder. See attachment.
![my_tracks](https://cloud.githubusercontent.com/assets/15245281/17104275/d3c17fd0-528a-11e6-8b20-bc9504303e17.png)

**Comment by martijnv-telenav** [comment]
@alexandrui-telenav does this still exist?

**Comment by james2432** [comment]
Yes still exists 
![tmp_5090-screenshot_20160810-18292831147627](https://cloud.githubusercontent.com/assets/498547/17573449/730171e6-5f28-11e6-9858-acf65df3e0f0.png)

**Comment by iav** [comment]
Now deletind image really deletes not current image on a display, but previous.

**Comment by hbogner** [comment]
Delete sequence deletes images, but leaves sequences on the web, and on the map.

**Comment by bipbipBE** [comment]
In my case, if I delete an image at the end of the track, it's correctly deleted but the path is deleted at the beginning

**Comment by hbogner** [comment]
I used this sequence for testing upload_photos_by_exif.py script.
Uploaded and deleted 3 times for test purposes, and the sequence and it's info is still shown.
Take a look:
http://openstreetview.org/map/@45.48046211462135,15.552319586277006,18z

**Comment by bogdan-telenav** [comment]
We are working on this. 
Photos are deleted but we have to clear in the  database the track
