### ISSUE TITLE
uploaded track is not shown correctly, map-matching very poor

### ISSUE THREAD

**Issue by developery-nl** [kartaview/openstreetcam.org#107]
I have uploaded several tracks. They are not shown by their gps location on the openstreetcam map but as far as I can see they are 'mapmatched'. But it looks very ugly, and incorrect, many sidestreets are colored as part of my tracks. And my gps is not soo bad.

So:
- please correct the mapmatching algorithm OR just plot the measured gps trace without mapmatching

**Comment by seb-1204** [comment]
I have to second that. The roads I covered with photos have been added to OSM about 1 month ago. 

See [here](http://openstreetcam.org/map/@24.76912258158007,54.96768951416016,12z)
![osc bad matching not per gms](https://cloud.githubusercontent.com/assets/307449/23506974/529d8db8-ff64-11e6-9190-e2861f978695.png)

**Comment by mirunac-telenav** [comment]
As of this month, your trips are being matched with OSM roads much more accurately. If your trip goes off-road, we will no longer force it onto a nearby road when we display it. If individual photos captured during your trip are too far from a road, they will instead show up as individual points on the website. Existing trips are re-evaluated as well.

**Comment by JiudanZheng** [comment]
@developery-nl , @mirunac-telenav has provided a detailed explanation. We will close this ticket.

**Comment by felixbecker2** [comment]
I today also made some contributions to KartaView.

I travelled on the tram and took pictures from the tram's rear window, then I was walking a footpath.

The matching was completely wrong. I was walking at the tram stop in one direction, the stop is in between two roads. The fotos were matched sometimes to the one, sometimes to the other road. But not to the tram stop's platform (which is mapped!). Then I was on the tram. Partly, the tramway goes distinct from the road. It was matched to nearby roads. At the end, I was walking a footway. The matching for some time stayed at the road, only when the distance to the road got too big it "jumped" to my footpath.

Please allow for advanced matching settings in the app (e.g. to specify on which map features I am walking/ riding/ ... to match against those, which also can be rail lines or waterways, or if I am in an unmapped area), or turn off map-based matching completely and calculate matching by extracting image features (like panorama stitching tools do).

Regards!
