### ISSUE TITLE
OSC misreads speed limit signs

### ISSUE THREAD

**Issue by allanmustard** [kartaview/openstreetcam.org#108]
I see two issues with OSC's reading of speed limit signs.  It has trouble reading LED signs (common in Ashgabat) and fluctuates among 40, 60, and 80 when trying to read 60.  In addition, it consistently misreads 4.5 M height limit signs (near bridges) as 40 kph speed limit signs.

**Comment by mirunac-telenav** [comment]
hi @allanmustard - (if it's still valid) can you provide a link so we can check on which track this happened? We've never run or detection model in Turkmenistan, so this is odd. Also, we don't have a training set for height limit signs yet.
