### ISSUE TITLE
No link to feedback etc. on the user's page

### ISSUE THREAD

**Issue by jidanni** [kartaview/openstreetcam.org#112]
Let's say I end up on my
http://openstreetcam.org/user/jidanni
page.

Well there is no link to feedback at the bottom, etc. No link to Help, etc.

**Comment by mirunac-telenav** [comment]
Hey @jidanni - the feedback button is one step (back) away from your user profile. 
It redirects you here, as you probably already know. 
This is how it was thought of, initially. 
If people will have trouble in finding it, we'll probably rethink its placement.

**Comment by jidanni** [comment]
(Well e.g., Google always makes sure to have a Feedback button on all pages.)

**Comment by miruna-craciun** [comment]
@jidanni Google has a team of engineers for every web page; we aspire to become like that one day. 
Meanwhile, you can send your feedback to these channels: 

[Facebook](https://www.facebook.com/kartaview)
[Twitter](https://twitter.com/kartaview)
[Email](mailto:geo.kartaview@grabtaxi.com )
[Github](https://github.com/kartaview)
