### ISSUE TITLE
Please update the Ashgabat map!

### ISSUE THREAD

**Issue by allanmustard** [kartaview/openstreetcam.org#117]
The Ashgabat map is sorely out of date.  Could you please update it to the current map so I can use the OpenStreetCam images more easily?  Please!

**Comment by ToeBee** [comment]
Yeah, it looks like the base map is now coming up on being a year out of date :(

**Comment by allanmustard** [comment]
I have switched to Mapillary since it a) keeps the base map up to date
and b) has an interface with ID, my preferred editor.

**Comment by ToeBee** [comment]
Well Mapillary uses MapBox tiles which... actually aren't being updated at the moment either :( But at least they are only a couple of months out of date at this point.

**Comment by bhousel** [comment]
> has an interface with ID, my preferred editor.

Hey @allanmustard - iD will be supporting OpenStreetCam very soon, see https://github.com/openstreetmap/iD/pull/4499

**Comment by allanmustard** [comment]
Mapillary also has the advantage of not tying images to an existing way,
which makes mapping new (or modified) streets much easier.

**Comment by miruna-craciun** [comment]
hey @allanmustard, everything you mentioned has happened in the meanwhile: 

1. KartaView now uses Mapbox tiles, which get updated more frequently
2. ID editor has been integrated with KartaView front end
