### ISSUE TITLE
Incorrect use of OAuth

### ISSUE THREAD

**Issue by ToeBee** [kartaview/openstreetcam.org#13]
I mentioned this to one of you at SOTM-US but looking at it some more I think you guys are using OAuth in a way that it isn't really intended to be used. The intended use of getting an OAuth token from osm.org is to make authenticated requests back to the OSM API on the user's behalf without needing to know the user's password. You are using it as an authentication mechanism for your own site. What you are looking for is OpenID or something like that. I don't think OSM provides this.

The result is this misuse of OAuth can be seen on my osm.org account settings page:
![image](https://cloud.githubusercontent.com/assets/348948/17145925/0af06dbc-5322-11e6-9f48-2061089082b8.png)

All other applications in that list have a single token issued per installation of that application and persist the token locally to keep issuing requests to the API as me.

**Comment by tomhughes** [comment]
Well authenticating with OAuth is pretty much accepted these days, even if it wasn't what OAuth was originally intended for, but people that do that should hang on to the token rather than getting a new one each time like this.

**Comment by ToeBee** [comment]
Well in that case, it might be good to set up a different application keys for the mobile app and the website. I went through and revoked a bunch of tokens to clean up my settings but this broke the android app. It still uploaded pictures but they vanished into `/dev/null` and never showed up in my profile. If you had a separate key named `OpenStreetView - Android` or something like that it would help in keeping things groomed.

**Comment by tomhughes** [comment]
Well ideally yes they would use different application keys, but even so it would be OK to have one token for each, just not to generate a new one on each use.

**Comment by mvexel** [comment]
Agreed we should do this more cleanly @alexandrui-telenav can we track this internally?

**Comment by james2432** [comment]
I was going to enter the same bug, very annoying having to login every 3-4 hours

**Comment by alexandrui-telenav** [comment]
Sorry for the late reply! We started a new sprint today and this issue is included. Will keep you guys posted, thanks for raising this.

**Comment by iagsav** [comment]
Hello, I have same bug

**Comment by grinapo** [comment]
Great to see progress in action! :-P

**Comment by mirunac-telenav** [comment]
@ToeBee is this issue still valid?

**Comment by ToeBee** [comment]
Kind of. You are still using the same kind of authentication. But at least now the session on your website seems to last a LOT longer so I am no longer being asked to authorize it every time I visit the website. 

It would still be nice to use a separate developer key for the website and the app to distinguish them in my OSM settings.
