### ISSUE TITLE
purple track not displayed for processed upload

### ISSUE THREAD

**Issue by rwelty1889** [kartaview/openstreetcam.org#219]
this issue is similar to what Clifford Snow describes in his comments on now-closed issue #197. i uploaded a track, it has been processed, and it is not rendered in purple on the home view in openstreetcam. this is the track:

https://openstreetcam.org/details/1444178/1/track-info

it captures the south end of Grand Street, but there is no purple line on display:

https://openstreetcam.org/map/@42.642822109432565,-73.75858604907991,18z

**Comment by rwelty1889** [comment]
this actually seems worse than described. certain recent tracks of mine that had been displayed are now no longer appearing on the site.

**Comment by cliffordsnow** [comment]
Maybe the questions is how long does it take for the openstreetmap.org to update when we upload? I expected that as they uploads were process that they would appear on the website.

**Comment by rwelty1889** [comment]
they had been appearing as soon as the upload completed. but now some that had previously displayed are no longer being displayed. something is busted.

**Comment by rwelty1889** [comment]
the checkbox for "my tracks only" does not appear to be doing anything anymore as well.

**Comment by joeybab3** [comment]
> the checkbox for "my tracks only" does not appear to be doing anything anymore as well.

I came here to report this exact thing but stumbled across your issue as well. I think they just updated something with how the purple tracks display and now it takes a few days for new tracks to show up.

**Comment by rwelty1889** [comment]
i noticed other anomalies in the website, i think there's something broken in processing flow. newly uploaded tracks never pass into the processing stage now, for one.

**Comment by rwelty1889** [comment]
this is looking somewhat fixed now. maybe even entirely fixed.

**Comment by rwelty1889** [comment]
ok, purple tracks not displayed seems fixed. the my tracks check box is not yet fixed from what i can see. the headline for this ticket is about purple tracks, and there's a separate ticket for "my tracks" so i'll close this one.

**Comment by alexandrui-telenav** [comment]
@rwelty1889 this was indeed fixed, what happened is that a few days ago our dev added all historic unmatched points to the matching queue (to correct older tracks that would not show up on the map). This delayed matching incoming data for a few days unfortunately..
There's still a bunch of older tracks to be run but we'll add it in small batches not to interrupt live data significantly.
'My tracks only' will be back in a few days, probably with extended functionality.

**Comment by rwelty1889** [comment]
the delay on purple tracks seems to be a thing again.

**Comment by cliffordsnow** [comment]
I'm seeing the same as @rwelty1889

**Comment by rwelty1889** [comment]
5 days without any purple track updates now.

**Comment by joeybab3** [comment]
I've noticed that the delay is in the web interface but the purple tracks show up quickly in the mobile app, can anyone else confirm this behavior?

**Comment by rwelty1889** [comment]
this seems to a degree to be true. i do have some old tracks that don't show up in either place, but most of my recent uploads do show up on my iphone.

**Comment by rwelty1889** [comment]
went back to check. the one that was missing from both was an upload oversight, so yes, it appears the phone/tablet app is working where the web app is not.

**Comment by JiudanZheng** [comment]
@rwelty1889 , I could see the track 1444178 on the web main page right now. Could we close this ticket?

**Comment by zhaitianduo** [comment]
Closing the ticket as we think we resolved this from our side, feel free to reopen if you found the problem still exists
