### ISSUE TITLE
Support for 360 photos in sequence viewer

### ISSUE THREAD

**Issue by james2432** [kartaview/openstreetcam.org#222]
https://openstreetcam.org/details/1454834/0/

Doesn't create a sphere despite it having the Metadata

**Comment by NathanBlais** [comment]
I would like this feature as well. So I can capture & upload 360 images instead of driving in a location multiple times with different camera placements.

**Comment by SviMik** [comment]
From what I can see in the details, it doesn't even recognize the projection:
```[projection] => PLANE```

All the metadata in the fullsize image is preserved though, which makes it possible to make a third-party viewer.

**Comment by SviMik** [comment]
I suddenly found that the viewer does support 360 photos, see example:
https://openstreetcam.org/details/2736614/0/track-info

You just need to add projection=SPHERE to your requests when uploading.
You can also add shotDate to enable the "Recorded at" field.

**Comment by zhangtiedong0912** [comment]
@james2432  @NathanBlais  hi we support 360 , It depends on the device you're using, like a GoPro. I will close this issue, you can open a new one if you have other question.
