### ISSUE TITLE
cannot delete sequence

### ISSUE THREAD

**Issue by rwelty1889** [kartaview/openstreetcam.org#224]
this sequence consisted of only one picture from my GoPro:

https://openstreetcam.org/details/1472970/1/track-info

i would just as soon delete it, but i cannot. it is displaying uploading, and when i click on the delete icon, i get this:

"Photo cannot be deleted! 400 - Bad Request - 671: The status is incorrect. The sequence of the photo you are tring to access is in processing"

please advise.

**Comment by JiudanZheng** [comment]
@rwelty1889 , this has been fixed. Could you please try again? Thanks!
