### ISSUE TITLE
details api not working

### ISSUE THREAD

**Issue by yehenm** [kartaview/openstreetcam.org#234]
I used to be able to extract osc metadata using the details api, following suggestions on #109 a couple months back. However, the api is not responding now using a parameter id='track-id'. Is there a known problem or an alternative link to access osc track metadata?

Thanks,

**Comment by joeybab3** [comment]
What url are you using to access the details?

**Comment by yehenm** [comment]
http://www.openstreetcam.org/details?id=585963
with the sequence id

**Comment by zhangtiedong0912** [comment]
@yehenm  hi you use a wrong url , the right is like this [https://kartaview.org/details/585963/0/track-info](url) , i will close this issue. you can reopen it if you still meet this issue.
