### ISSUE TITLE
cannot delete track being uploaded

### ISSUE THREAD

**Issue by rwelty1889** [kartaview/openstreetcam.org#237]
the following track has serious sequence problems:
https://openstreetcam.org/details/1964457/1/track-info
i have aborted the upload since there's no real point until i fix the sequencing, but the web interface does not appear to let me delete the track. the message given is
ERROR There was a problem deleting sequence!

**Comment by BalooUriza** [comment]
Also running into this problem trying to delete a track that's in a similar state.

**Comment by zhangtiedong0912** [comment]
@rwelty1889  @BalooUriza Thanks for your feedback, fixed , please check try again . i will close this your can reopen it if you still meet this issue.
