### ISSUE TITLE
unclickable track

### ISSUE THREAD

**Issue by minty** [kartaview/openstreetcam.org#242]
https://openstreetcam.org/map/@55.93268804337846,-3.2674133777618413,16z

re: "Stenhouse Drive"

It shows a purple line, indicating there are pictures & indeed, I uploaded that track today.

But if I try to click it, I get a brief spinny icon appear bottom middle of the map, but I do not get the bar along the bottom to link to the appropriate track & see the images.

Compare to "Saughton Road" on the same link, just to the south of Stenhouse Drive.  That purple line IS clickable, and DOES bring up the bar that links to the relevant tracks.

I've noticed this problem with other tracks I've uploaded before ... this one was uploaded over a month ago, but still won't bring up the bar at the bottom when you click on "Craigmount View" for example.

https://openstreetcam.org/map/@55.94798631503492,-3.2980817556381226,17z

**Comment by joeybab3** [comment]
I think that OSC is not processing tracks right now and what you are describing is in line with some of the issues I see when openstreetcam doesn't process a track for one reason or another or just halfway processes a track.

**Comment by Shura0** [comment]
Sometimes tracks are unclickable even when its processed. Some days they are clickable, some days not

**Comment by miruna-craciun** [comment]
@minty we've come a long way since this issue, our processing pipeline has improved with time. the routes are clickable atm.
@Lining-grab can you confirm that this is no longer an issue?

**Comment by Lining-Grab** [comment]
@miruna-craciun Yeah, I think this is not a issue that a track is deleted but the purple line still shows.
