### ISSUE TITLE
Waylens records while the car is off

### ISSUE THREAD

**Issue by joeybab3** [kartaview/openstreetcam.org#258]
As much as I love having 10k extra points, I prefer to earn my points by traveling new roads rather than my way lens recording while the car is off...

Something seems to trigger the way lens to start recording when it doesn't have OBD (since the car is off) and it basically will go until the car turns off.

This combined with the inability to delete a track currently means that I'm stuck with 10k images of one of my friends garages...

https://openstreetcam.org/details/2214094

**Comment by chip-grab** [comment]
Joey, you can delete the sequence if you go to your profile on web. For each sequence there is a little delete icon on top-right of tracks preview. 
Not sure though why did Waylens record it. 🤷‍♂️

**Comment by joeybab3** [comment]
@chip-grab That was not the case previously, It has been deleted now but previously it would fail out. In the meantime, I still can't delete individual photos that were filmed such as when I don't want to delete the whole track, but instead just a few images.

![Screen Shot 2020-06-19 at 9 24 48 AM](https://user-images.githubusercontent.com/2829457/85156506-049ef000-b20f-11ea-80e5-d92367c2b903.png)

**Comment by joeybab3** [comment]
Adding to this, it is caused by the car being in a garage and the GPS floating around which then makes the waylens think the car is moving despite the obd dongle being connected.

Nothing you can really do about it if the obd dongle isn't connected but I think it might be useful to see if OBD reports the car moving and if it doesn't then don't start the sequence.

**Comment by miruna-craciun** [comment]
@joeybab3 the "detele" function is working now. 
The bitter part is that KartaView no longer offers support for Waylens cameras.🙁

**Comment by joeybab3** [comment]
> @joeybab3 the "detele" function is working now.
> The bitter part is that KartaView no longer offers support for Waylens cameras.🙁

Is that a new development? For those of us who use these cameras what should we do?

**Comment by miruna-craciun** [comment]
@joeybab3 you can reach out here: support@telenav.com
the waylens project was not carried over to Grab.
