### ISSUE TITLE
Crash and other Problems

### ISSUE THREAD

**Issue by KarlFrederik** [kartaview/openstreetcam.org#265]
I tried to upload today 5 Track.
The iOS app crashed about 15 times and at the last crash, one of the tracks just disappeared and is now gone.
Also, only 2 of the 5 Tracks are online. 
I can't note a problem in the iOS app, because it loads about 10 minutes and then crashes.
It is really annoying. I also just wanna switch from mapillary to OpenStreetcam due to Facebook, but i can't use that if it has so many buggs and i can't really upload anything.

Thank you

**Comment by chip-grab** [comment]
Karl, can you please provide us the link to your 2 online sequences?

**Comment by KarlFrederik** [comment]
> Karl, can you please provide us the links to your 2 online sequences?

Yes, 
1: [https://openstreetcam.org/details/2727814/0/track-info](url)
Track ID: 2727814
2: [https://openstreetcam.org/details/2727798/0/track-info](url)
Track ID: 2727798

**Comment by KarlFrederik** [comment]
Today I Uploaded 4 new Tracks and 2 of them disappeared. Now there are 4 online and 4 are gone.
