### ISSUE TITLE
Suggestion: Make a Forum

### ISSUE THREAD

**Issue by KarlFrederik** [kartaview/openstreetcam.org#268]
I would really like a forum where members can talk to other Members and exchange knowledge or team up to capture Towns or villages.
I think it would be a nice idea.
Also, it is a good way to answer questions if somebody has some.

**Comment by joeybab3** [comment]
Though I agree a forum would be very helpful, there is currently a Subreddit at /r/openstreetcam if you would like to join and hopefully get some more dialogue going
