### ISSUE TITLE
openstreetmap.org authentication doesn't work again?

### ISSUE THREAD

**Issue by kudarisenmon** [kartaview/openstreetcam.org#269]
I am tring to log in with openstreetmap.org account, but It fails with a "Ups! Authentication failed!" message.
Is this the same issue as the one that was closed?

_Originally posted by @chip-grab in https://github.com/openstreetcam/openstreetcam.org/issues/261#issuecomment-648409733_

**Comment by miruna-craciun** [comment]
will close, working now.
