### ISSUE TITLE
360 sequences are stuck in PROCESSING state

### ISSUE THREAD

**Issue by SviMik** [kartaview/openstreetcam.org#270]
I tried to upload 360 images, but something went wrong:

<img src="http://svimik.com/oscstuck1.png">

All sequences are in PROCESSING state. I can view them, but other people have no access to them. They also show "invalid km" and didn't give me any points.

My profile (only I can see them, others will see just empty page):
https://openstreetcam.org/user/svimik
Sequence example (it will say "Ups! Sequence cannot be loaded... "):
https://openstreetcam.org/details/2736670/0/track-info

**Comment by SviMik** [comment]
This only happens with images with projection=SPHERE. I can upload 360 images with projection=PLANE and there's no issues with processing in this case, but then I'll miss the 360 viewer and the images will be displayed just as flat pictures.

**Comment by SviMik** [comment]
Okay, I got it. It takes 2-3 days to process 360 images. Not sure what's the reason though, plane images are available almost immediately. Not sure if I shall close the issue, would be really nice if @chip-grab said at least something :)

**Comment by chip-grab** [comment]
@SviMik,  360 imagery has less dedicated hard for processing and it is more resource consuming. This is why it takes longer than regular images. We are working on improving this. 
We recommend using SPHERE, the API was designed to have projection=SPHERE for 360 imagery.

**Comment by SviMik** [comment]
@chip-grab Thanks, that's what I'm doing now. I was afraid it'll never get processed, but now I see it works. I hope you can improve it, or at least make it visible to public as soon as it's uploaded.

**Comment by JiudanZheng** [comment]
@SviMik , I see all tracks you mentioned have been processed. We'll close this ticket.

**Comment by zhaitianduo** [comment]
Closing the ticket as we resolved this from our side, feel free to reopen if you found it still exists
