### ISSUE TITLE
Some tracks upload and never show up on the site/only part of the track shows up

### ISSUE THREAD

**Issue by joeybab3** [kartaview/openstreetcam.org#275]
This seems to be an issue with large tracks especially, but I recently drone almost 800 miles with my waylens and in total like 2 miles of that registered on the site. 

Not only that, but I even drove this stretch twice and neither one shows up. At this point, I'm once again questioning what the purpose of me using 90gb of data to upload these tracks is when the OSC server won't even acknowledge them.

**Comment by panthersdude2001** [comment]
Yep, I agree with you too. I took a very long sequence from my house to another house we were looking at in Clinton. No evidence of it seen at all on OSC. Another sequence took about 20 days to show up, and that was where I went to my local animal hospital.

**Comment by panthersdude2001** [comment]
![image](https://user-images.githubusercontent.com/44646536/88579456-0df25800-d018-11ea-9f84-24be87f0b10a.png)
This is what the tracks shows now. No evidence of NC 55 going into I40, which is supposed to be purplized now.
@chip-grab wondering why is this the case?

**Comment by joeybab3** [comment]
Not sure if this is an issue anymore, closing until i can find it happening in the wild again.
