### ISSUE TITLE
Waylens uploads show no OBD despite it being connected

### ISSUE THREAD

**Issue by joeybab3** [kartaview/openstreetcam.org#278]
Uploads from my waylens now show no OBD on all tracks even though I always wait for the obd dongle to connect before beginning driving.

See: https://openstreetcam.org/details/2903066/0/track-info

**Comment by joeybab3** [comment]
Another example, seems it marks the whole sequence as no obd of the first image doesn't have the dongle connected yet

**Comment by miruna-craciun** [comment]
Closing as obsolete ( cc #258 )

**Comment by NathanBlais** [comment]
It should still be classified as an open bug though right? It should still be labeling the images with OBD as still having it. Or does it not track the OBD values at all if it is connected part way?
