### ISSUE TITLE
Tracks only partially processing

### ISSUE THREAD

**Issue by joeybab3** [kartaview/openstreetcam.org#279]
Does anyone who maintains this repo even read these issues? 
Should I keep posting them as I encounter them or am I just contributing to a lost cause here?

Here is a track I filmed with 13.5k images:
https://openstreetcam.org/details/2907526/13273/track-info

You may notice that for this track I received less than 1 point per image at a whopping total of 576 points for 13,576 images.

The track doesn't show up in "my tracks" on the map which usually for me means that it stopped processing or had some sort of issue. 

I used to be able to tell if there was a processing error because traffic sign detection isn't there for images that didn't process but as many of you probably know traffic sign detection hasn't worked in months. 

I'm not asking for a quick fix, but a response that someone is still maintaining this project or that these issues are being read would be much appreciated.

**Comment by chip-grab** [comment]
@joeybab3, yes, we do read all the issues raised here, we do appreciate it. Unfortunately though, the team is understaffed and fixing the issues you point out is not always working as fast as we want.
The points allocation is an issue that we are aware of, and we give our best to bring the fix for it soon. Don't worry, your photos will get the points that they deserve. 
Thank you!

**Comment by joeybab3** [comment]
@chip-grab Thanks for the response, I'm not asking for a quick fix here but openstreetcam has given us no updates in months. 

Issues on here go largely unanswered and unacknowledged by your team, I opened this one in October of last year and it is still a problem: https://github.com/openstreetcam/openstreetcam.org/issues/245

I don't want to just tag you every time I have a problem as I'm not trying to be annoying but it seems that you are the only member of your team working on Github.

I'm don't really even care about the points here, I'm just trying to get the imagery I upload to process or at least to show up on the site.

**Comment by tigren** [comment]
@joeybab3 sorry for reply so so late, I processed the sequence again, the points is  58029 now
