### ISSUE TITLE
Mapbox/background tiles not displaying (403)

### ISSUE THREAD

**Issue by joeybab3** [kartaview/openstreetcam.org#283]
Seems like you may have forgotten to renew your mapbox license or something as the map now only shows tracks and not the underlying streets. 

The console shows a 403 error being returned from mapbox.

![Screen Shot 2020-08-27 at 2 16 10 PM](https://user-images.githubusercontent.com/2829457/91495752-dcb3b480-e86f-11ea-80de-0e7d56c1fc85.png)

The app(iOS) still shows tiles correctly.

**Comment by joeybab3** [comment]
Seems fixed... for now

**Comment by joeybab3** [comment]
Still an issue

**Comment by joeybab3** [comment]
It's happening again

**Comment by joeybab3** [comment]
Seems to be an on and off issue, leaving it open for now.

**Comment by JiudanZheng** [comment]
@joeybab3 , are you still suffering from this issue? I tried a couple of times, not saw this issue any more.

**Comment by joeybab3** [comment]
@JiudanZheng not on kartaview it seems
