### ISSUE TITLE
APIs for obtaining street-view images

### ISSUE THREAD

**Issue by bhparijat** [kartaview/openstreetcam.org#284]
Hi,
Does OpenStreetCam have any APIs exposed that I could use for obtaining street-view images for lat, long pairs? 
Thanks

**Comment by bhparijat** [comment]
Also, how to get the auth key generated?

**Comment by SviMik** [comment]
Sure, check the documentation here: http://api.openstreetcam.org/api/doc.html
I believe `List of sequences` can be used with its `bbTopLeft` and `bbBottomRight` parameters, or `Get Nearby Photos` seems to be even more precise, although I've never tried that one personally.

**Comment by bhparijat** [comment]
Does this database have images for most of the latitudes, longitude pairs? I see that it returns 
`{
    "status": {
        "apiCode": "600",
        "apiMessage": " The request has been processed without incidents ",
        "httpCode": 200,
        "httpMessage": "Success"
    },
    "currentPageItems": [],
    "totalFilteredItems": [
        "0"
    ]
}
`
for most of the pairs that I have. I use url http://openstreetcam.org/1.0/list/nearby-photos/  and specify lat,lng, radius=500 and username in body.

Am I doing anything wrong?

**Comment by alex-grab** [comment]
I think _username_ is a filter in that request (retrieving data contributed by a specific user), if you're interested in all imagery available at a lat-lon you should leave it out. Correct me if I'm wrong @chip-grab

**Comment by ALFURJANI** [comment]
Dear all,
We would like to inform you that the OpenStreetMap community of contributors has launched the National street-imagery level project for the whole of Libya.
actually we are facing some technical and operating issues with the OpenStreetCam platform, on both; mobile apps and desktops as described below:
- we can't browse and explore the uploaded photos on the OSC platform in Libya.  
- the Arabic language text on the map is fragmented and inversed in the direction.
we look forward to more cooperation.
Best regards 
Abdurahman AL Furjani
OpenStreetMap Libya 
+33767764709

**Comment by alex-grab** [comment]
@ALFURJANI this is probably a separate question from the issue. I see a very limited amount of imagery in Libya like [this](https://openstreetcam.org/details/2969018/86) recording but we don't see any technical issues. What data was uploaded should be available.
Can you share more details?

**Comment by ALFURJANI** [comment]
I'm Sory to ask such a question in this issue, anyway as I asked before the text in the Arabic language appears fragmented and left to right, and during the last seven days we uploaded photos to the OSC platform but the imaging path or sequence can not be visualized on the map!
regards

**Comment by ALFURJANI** [comment]
![Arabic language](https://user-images.githubusercontent.com/29812955/92854453-5e1f5100-f3f1-11ea-9cc4-c540911a2f85.PNG)
