### ISSUE TITLE
Can't delete a photo

### ISSUE THREAD

**Issue by Xevib** [kartaview/openstreetcam.org#285]
# Description
- I try to delete a photo and I get "Photo cannot be deleted! 400 - Bad Request - 671: The status is incorrect. The photo you are tring to access is deleted or does not exist."

**Comment by joeybab3** [comment]
![Screen Shot 2020-09-04 at 1 47 07 PM](https://user-images.githubusercontent.com/2829457/92283643-2e35f200-eeb5-11ea-904d-fb07559756af.png)
I think this has been an issue since #226 but I can confirm it's still a problem :/

**Comment by patchie** [comment]
I got the same error message.

**Comment by tigren** [comment]
please try delete photos on https://kartaview.org/ now

**Comment by patchie** [comment]
It works. Thanks!
