### ISSUE TITLE
Tracks aren’t processing again

### ISSUE THREAD

**Issue by joeybab3** [kartaview/openstreetcam.org#288]
I’m used to waiting a few days for tracks to show up but it’s been 6 days since I’ve had a track process at all, currently everything I’ve uploaded since September 6th sits at 0 points. More importantly than points though is that the tracks sometimes just never show up. I’ve had about 30% of the tracks I’ve filmed just disappear and never show up on the site in the last few days which is a much higher rate of loss than usual.

**Comment by ALFURJANI** [comment]
Hi, joeybab3
we are facing the same issue in Libya !!

**Comment by SviMik** [comment]
According to the leaderboard it seems that no one has received any points this week. @chip-grab please tell it's gonna be fixed!

**Comment by joeybab3** [comment]
The last track I've found that processed ~successfully~ seems to indicate that this issue began occurring ~13 days ago between September 3rd and 4th.

**Comment by alex-grab** [comment]
Oh.. looking into that @joeybab3

**Comment by joeybab3** [comment]
> @joeybab3 I don't see any pending recordings on your account though, all seem published now.
> 

Please note that none of them have any points and aren’t viewable anywhere other than on my profile.

They are published but have not processed.

**Comment by SviMik** [comment]
Could you check this account please?
https://openstreetcam.org/user/macsico
The API gives me 484 sequences, but the profile says "Tracks:91"

**Comment by ALFURJANI** [comment]
@alex-grab
https://openstreetcam.org/user/aal-ldyn-bn-saayd
https://openstreetcam.org/user/abdurahman-al-furjani

**Comment by EndlessIdea** [comment]
Sorry for the inconvenience. We are fixing these tracks now, hopefully these tracks will be processed within 3 or 4 days. I will update the progress here.

**Comment by funkydancer** [comment]
Sorry for the inconvenience. We are fixing these tracks now, hopefully these tracks will be processed within 3 or 4 days. I will update the progress here.

**Comment by joeybab3** [comment]
Tracks do indeed seem to be processing again, hopefully this won't keep happening once a month

**Comment by SviMik** [comment]
A different kind of bug, but maybe you could look into that too? There are bunch of tracks stuck in `UPLOAD_FINISHED` state (on the website it's displayed like `5 TRACKS PROCESSING` in user's profile).
For example, tracks 3006122, 3006022, 3004754, 3004390, 3004194, 3002318, 3001974, 2999082, 2995986, 2993570, 2988066, 2977314, 2971978, 2971902, 2964894, 2964866, 2963994, 2963530, 2962762, 2958114, 2942146

**Comment by joeybab3** [comment]
@funkydancer @alex-grab i see that it’s processing again but it’s skipped some of my tracks in doing so... this isn’t that abnormal as I have tracks that never processed from a while ago but is there no way to flag a track to be reprocessed?

**Comment by EndlessIdea** [comment]
@joeybab3 Could you also provide your account link? I'm checking the issue.

**Comment by EndlessIdea** [comment]
Regarding the points issue, it may take a day or two to finish as the compute resource is limited? sorry for the inconvenient time.

**Comment by EndlessIdea** [comment]
@SviMik Thanks for submitting this bug. I have found such tracks and fixed them. Now these tracks should be in FINISHED state.

**Comment by joeybab3** [comment]
> @joeybab3 Could you also provide your account link? I'm checking the issue.

My username is the same on openstreetcam — joeybab3

**Comment by joeybab3** [comment]
See #275 and #254 if you need some older examples, they still have not been processed

**Comment by EndlessIdea** [comment]
@joeybab3 For these tracks, I think you mean they have no points, right?

**Comment by joeybab3** [comment]
@EndlessIdea that is part of it, they don’t show up on “my tracks” either when the filter is enabled on the main map.

**Comment by SviMik** [comment]
> https://openstreetcam.org/user/macsico
> The API gives me 484 sequences, but the profile says "Tracks:91"

Now it says "Tracks:481". 3 tracks got lost somewhere in the process. Not a critical thing, but may indicate some bug that is still present.
The lost tracks are: 3003786, 3003774, 3003750

**Comment by ALFURJANI** [comment]
hi, this for the profile 
https://openstreetcam.org/user/mohamedkenan
Track ID
3068634
3068518
3068474 
3067218 
3064478
3061614
3061410
3060690
3060618 
3060138

**Comment by ALFURJANI** [comment]
@funkydancer 
hi, this for the profile
https://openstreetcam.org/user/mohamedkenan
Track ID
3068634
3068518
3068474
3067218
3064478
3061614
3061410
3060690
3060618
3060138
https://openstreetcam.org/user/mohamedkenan
Track ID
3073770
3075302
3071814

**Comment by ALFURJANI** [comment]
what's going on?

**Comment by JiudanZheng** [comment]
@ALFURJANI , I could see these tracks right now.

**Comment by zhaitianduo** [comment]
Closing the ticket as we resolved this from our side, feel free to reopen if you found it still exists
