### ISSUE TITLE
Blurring processing blurs traffic signs sometimes

### ISSUE THREAD

**Issue by joeybab3** [kartaview/openstreetcam.org#289]
See this image, it would be useful to be able to report a false censor sometimes
https://openstreetcam.org/details/2903066/9417/track-info

**Comment by alex-grab** [comment]
Agree @joeybab3

**Comment by joeybab3** [comment]
@zhaitianduo can you guys try and spare a response when closing issues? I understand if you don't see any way to fix or deal with the reported issue but it would be helpful to your userbase to at least leave a comment on why you chose to close the issue.

**Comment by zhaitianduo** [comment]
Hi @joeybab3 
Do you have any further issue or questions on this issue? 
I considered this as a feature request and  I noticed Alex already responded. We have some internal tickets to improve this so I closed this one.
