### ISSUE TITLE
Map filter options are slightly hidden by navbar on mobile 

### ISSUE THREAD

**Issue by joeybab3** [kartaview/openstreetcam.org#290]
I’m not sure if mobile browsers are even intended to be supported but on mobile the options (specifically to view “my tracks”) are hidden behind the navbar.

![AB600CD3-110E-4CA3-BCA6-9E92553E97B7](https://user-images.githubusercontent.com/2829457/93714626-e6e86c00-fb18-11ea-8b72-45648049243e.png)

**Comment by zhaitianduo** [comment]
![image](https://user-images.githubusercontent.com/5261179/103869205-fa8a0380-5104-11eb-896e-b243476f6430.png)
Hi Joey, after the rebranding to KartaView, it looks like this. I will close the ticket. Feel free to reopen after you found new issues, thanks!
