### ISSUE TITLE
recently processed tracks not showing up on main display

### ISSUE THREAD

**Issue by rwelty1889** [kartaview/openstreetcam.org#296]
the tracks are labeled processed, they have points which appear to be credited to the leaderboard totals, but they do not show up in purple on the main display.
the display used to be nearly instant; for some time now there has been a lag of a several days, but these tracks were uploaded more than a week ago and do not yet appear. this is a real usability problem as i use the map display in deciding if i want to take any alternate routes to improve coverage.

example: http://openstreetcam.org/details/3088794/1/track-info

**Comment by ALFURJANI** [comment]
we are facing the same problem in Libya 
https://openstreetcam.org/user/aal-ldyn-bn-saayd
https://openstreetcam.org/user/mohamedkenan
https://openstreetcam.org/user/osama-elhaddad
https://openstreetcam.org/user/abdalla-altaboni
https://openstreetcam.org/user/salah-alseleni
https://openstreetcam.org/user/ahmed-elgehani
https://openstreetcam.org/user/saad-abu-matary
https://openstreetcam.org/user/noredeen-imto
https://openstreetcam.org/user/elhusadi

**Comment by joeybab3** [comment]
Yeah the purple tracks are not processing but if you go to openstreetmap and have it show images they are there. 

As for the sign detections that hasn’t worked for over a year now I believe so I’m starting to think it’s not intended to work.

**Comment by JiudanZheng** [comment]
@rwelty1889 , we've fixed the showing up issue for http://openstreetcam.org/details/3088794/1/track-info. Could you please confirm and close the ticket? Thanks.

**Comment by joeybab3** [comment]
@JiudanZheng That's for one track though? The data is not processing for any new tracks.

**Comment by JiudanZheng** [comment]
@joeybab3 , checked the tracks posted by you. There were 3 tracks on Oct 27 and one track on Oct 25 under processing. Depending on different images, processing may take a couple of days.

**Comment by joeybab3** [comment]
@JiudanZheng Yeah I checked and one track I took on the 23rd has gone in so it seems to be processing again. Most of my tracks from the last month or so are not on the main map but still "processed" in some regard.

**Comment by ALFURJANI** [comment]
@JiudanZheng could you please check my 33 tracks not yet shown up on the map 
https://openstreetcam.org/user/mohamedkenan
https://openstreetcam.org/user/aal-ldyn-bn-saayd
regards

**Comment by JiudanZheng** [comment]
@ALFURJANI ,I checked track 3186038 and 3186042 under Mohamedkenan. Both tracks could be seen on the main display. Also, I checked track 3192806 and 3192798. Both could be seen on the main display as well. Do you have a specific track that could show up? Thanks

**Comment by JiudanZheng** [comment]
@ALFURJANI , we have done some processing for the tracks you mentioned? Could you please check if those tracks can display on the map? Also, not sure if you raised one issue about the display issue on the app user profile? Could you please check as well? Thanks!

**Comment by JiudanZheng** [comment]
@rwelty1889 , I could see track 3088794 on the main display. Could you confirm this from your side? If everything is ok, could we close this ticket? I would close this ticket by this Fri. Thanks.

**Comment by zhaitianduo** [comment]
Closing the ticket as we resolved this from our side, feel free to reopen if you found it still exists
