### ISSUE TITLE
Some tracks not processed on main map, some not at all

### ISSUE THREAD

**Issue by joeybab3** [kartaview/openstreetcam.org#297]
Even though I have several issues still open about this it seems that the folks at grab would prefer we open separate issues to re bring these problems to their attention so here is the tracks that I'm aware of that have issues.

Not processed at all:
https://openstreetcam.org/details/3019178
https://openstreetcam.org/details/3018214
https://openstreetcam.org/details/3017430
https://openstreetcam.org/details/3016746
https://openstreetcam.org/details/3015450
https://openstreetcam.org/details/3015146
https://openstreetcam.org/details/3013278
https://openstreetcam.org/details/3010086

**Comment by joeybab3** [comment]
Adding to this, some are now giving me fewer points than there are images...
https://openstreetcam.org/details/3227489
https://openstreetcam.org/details/3227101
https://openstreetcam.org/details/3225401
https://openstreetcam.org/details/3224121
https://openstreetcam.org/details/3222525 (not processed at all)
https://openstreetcam.org/details/3221525
https://openstreetcam.org/details/3218398 (17k images and 470 points?)

**Comment by joeybab3** [comment]
Another partially processed track:
 https://openstreetcam.org/details/3242873

**Comment by joeybab3** [comment]
Some more:
https://openstreetcam.org/details/3277701 (8 photos out of 3070 processed...)
https://openstreetcam.org/details/3277121

**Comment by joeybab3** [comment]
@lining.guan Any help for these sequences?

**Comment by joeybab3** [comment]
Adding more to these:
Not on main map:
https://openstreetcam.org/details/3309165/0/track-info

Less points than images:
https://openstreetcam.org/details/3309161
https://openstreetcam.org/details/3309165

**Comment by joeybab3** [comment]
Not fully processed: 
https://openstreetcam.org/details/3309909
https://openstreetcam.org/details/3309881
https://openstreetcam.org/details/3309849
https://openstreetcam.org/details/3309845
https://openstreetcam.org/details/3309829

**Comment by JiudanZheng** [comment]
@joeybab3 , we've done some improvement and correction. I checked some tracks above. They have been processed successfully. Looks like all tracks you post before Dec 19 have been processed. Could you please confirm? If that is the case, could you please close this ticket?

**Comment by joeybab3** [comment]
@JiudanZheng while you are correct on the very first batch, nothing after that seems to be processed. I have removed the ones that appear to have processed from above.

**Comment by JiudanZheng** [comment]
@joeybab3 , thanks for the feedback. Could you please list the tracks in the new comment? A couple of batches above.

**Comment by joeybab3** [comment]
@JiudanZheng 
https://openstreetcam.org/details/3019178
https://openstreetcam.org/details/3018214
https://openstreetcam.org/details/3017430
https://openstreetcam.org/details/3016746
https://openstreetcam.org/details/3015450
https://openstreetcam.org/details/3015146
https://openstreetcam.org/details/3013278
https://openstreetcam.org/details/3010086
https://openstreetcam.org/details/3227489
https://openstreetcam.org/details/3227101
https://openstreetcam.org/details/3225401
https://openstreetcam.org/details/3224121
https://openstreetcam.org/details/3222525
https://openstreetcam.org/details/3221525
https://openstreetcam.org/details/3218398
https://openstreetcam.org/details/3242873
https://openstreetcam.org/details/3277701
https://openstreetcam.org/details/3277121
https://openstreetcam.org/details/3309165
https://openstreetcam.org/details/3309161
https://openstreetcam.org/details/3309165
https://openstreetcam.org/details/3309909
https://openstreetcam.org/details/3309881
https://openstreetcam.org/details/3309849
https://openstreetcam.org/details/3309845
https://openstreetcam.org/details/3309829

**Comment by JiudanZheng** [comment]
@joeybab3 , just checked. All these sequences have been processed.

**Comment by joeybab3** [comment]
@JiudanZheng the first sequence in the list is not processed however? It has 0 points? Are you sure they’re processed?

**Comment by JiudanZheng** [comment]
@joeybab3 , we've re-calculated points for these tracks. Could you please confirm?

**Comment by joeybab3** [comment]
Yes it appears I can finally let this issue rest.
