### ISSUE TITLE
Closing all open sequences?

### ISSUE THREAD

**Issue by moenk** [kartaview/openstreetcam.org#299]
There are quite a lot open sequences when the uploader crashed. I can neither close nor delete them. So an option would be crucial to close all open sequences if this is not done automatically after some timeout.

**Comment by SviMik** [comment]
If you can program, you can use the API call for closing: http://api.openstreetcam.org/api/doc.html
See ``Notify the server that the uploading has been finished``

**Comment by moenk** [comment]
Actually I tried to do that but I didn't understand how to place the secret token, usually in a bearer in the header, but this didn't work out. Simple code samples for the API in Python would be helpful, the uploader is too complex.
Anyway, I consider automatic closing as required feature for the platform, it does not make sense to keep changesets open for months.

**Comment by ybdx** [comment]
@moenk  this case is very special. Our team has to talk about how to close the sequences.   We will close the sequences after we decided on the solution.

**Comment by zhangtiedong0912** [comment]
@moenk  hi could you please check again? we remove some limit, user can delete unfinished sequence by themself now.

**Comment by moenk** [comment]
Confirmed, was able to delete unfinished sequences -  but now I have to scroll through over 5000 sequences, will take a while, a filter would be great.

**Comment by zhangtiedong0912** [comment]
@moenk  good suggestion . could you please add a new issue about add filter? it will more clear, i will close this issue If that's all right with you.
