### ISSUE TITLE
13 Tracks Stuck in "Processing" Limbo

### ISSUE THREAD

**Issue by GeekOnTheHill** [kartaview/openstreetcam.org#300]
3238109
3238157
3243069
3243089
3243105
3243109
3243121
3243125
3243193
3243197
3243201
3243205
3243209

Thanks.

**Comment by GeekOnTheHill** [comment]
Do you care to share where the processing tends to break down? My plan is to disable "video encoding mode" to see if that helps. Is it worth trying? Thanks.

**Comment by Lining-Grab** [comment]
Hi GeekOnTheHill, 
Sorry for the inconvenient time.
We had a stuck time for processing the photos, now it recovered, I think these trips will be processed in 2~3 days.

**Comment by GeekOnTheHill** [comment]
Okay, thank you.

**Comment by Lining-Grab** [comment]
@GeekOnTheHill Sorry for the late response, these tracks were all processed, please have a check when you are available.

**Comment by GeekOnTheHill** [comment]
Yep, they're all there now. Thank you.
