### ISSUE TITLE
Photo cannot be deleted! 400 - Bad Request - 690: An unexpected server error has occurred

### ISSUE THREAD

**Issue by GeekOnTheHill** [kartaview/openstreetcam.org#302]
I tried to delete a few photos and got the error in the title. The images are the last few in sequence 3309117, if that helps. Also, it was on the kartaview.org site, if that matters.

This isn't a huge big deal in this instance. I was going to delete the images because they were taken when the phone fell out of the mount, not because there was anything objectionable about them other than being useless. Just letting you know about the error.

On a positive note, the processing has been quick and flawless today. Thanks.

**Comment by tigren** [comment]
checking now

**Comment by joeybab3** [comment]
#226 and #285 covered this sort of, the photo actually does delete but just shows an error for some reason.
It's been that way for over a year like many of the other open issues on here.

**Comment by tigren** [comment]
@GeekOnTheHill this issue has been fixed, please try delete the photo again on https://kartaview.org/

**Comment by GeekOnTheHill** [comment]
> @GeekOnTheHill this issue has been fixed, please try delete the photo again on https://kartaview.org/

Sorry about the delay. Been busy this past week. Yes, it's working fine now. Thank you.
