### ISSUE TITLE
old tracks stuck in processing or no points assigned

### ISSUE THREAD

**Issue by thatoneiowan** [kartaview/openstreetcam.org#303]
Posting this because of the shift to KV.......

I have this old list of tracks stuck in processing:
https://openstreetcam.org/details/3217126/0/track-info
https://openstreetcam.org/details/3217086/0/track-info
https://openstreetcam.org/details/3217030/0/track-info
https://openstreetcam.org/details/3216946/0/track-info
https://openstreetcam.org/details/3216850/0/track-info
https://openstreetcam.org/details/2713894
https://openstreetcam.org/details/2713470

And then also these tracks that don't say processing but have no points assigned:
https://openstreetcam.org/details/3216850/0/track-info
https://openstreetcam.org/details/3216850/0/track-info
https://openstreetcam.org/details/2730594/0/track-info
https://openstreetcam.org/details/2714402/0/track-info
https://openstreetcam.org/details/2301506/0/track-info
https://openstreetcam.org/details/2065566

This one is stuck in Uploading:
https://openstreetcam.org/details/1588717

Thanks

**Comment by JiudanZheng** [comment]
We are looking at this. Will provide update later.

**Comment by moenk** [comment]
Automatic closing of uploads after one week would be great.

**Comment by JiudanZheng** [comment]
@moenk , at this moment, tracks 3216850, 3216946, and 3217030 haven't been processed successfully yet. Track 1588717 and 2065566 haven't got points. We are still checking these tracks. Others should be fine.

**Comment by JiudanZheng** [comment]
@moenk , right now only track 2065566 is waiting for the points.

**Comment by thatoneiowan** [comment]
> @moenk , right now only track 2065566 is waiting for the points.

2713894 and 2713470 currently show no point values on my end right now either.

**Comment by moenk** [comment]
Thanks, points are not really my problem, but it would be fine if open sequences could be close after some timeout.,

**Comment by JiudanZheng** [comment]
@thatoneiowan , your two tracks have got the points. @moenk , what do you mean by close?

**Comment by moenk** [comment]
When the upoloader crashed during upload the sequence remains open and is shown in state "uploading" forever.

**Comment by thatoneiowan** [comment]
> @thatoneiowan , your two tracks have got the points. 

I see points on these now. Thank you! I'll let @moenk start a new thread if he wants to for his idea (which I support 100%).

**Comment by JiudanZheng** [comment]
@moenk , what uploader are you using? App or other tools? We will see how to improve this.

**Comment by moenk** [comment]
The python uploader from this repo of course, also I posted a fix already that works for me.
