### ISSUE TITLE
Can't browse track in "processing" state : CORS related

### ISSUE THREAD

**Issue by laurentriffard** [kartaview/openstreetcam.org#304]
Hi, 

2 days ago, I captured a new track and uploaded it. Now, this track is in "processing" state.

When I try to browse this track, no picture is displayed. The left handed menu  (Track info, Edit OSM, Traffic Sign, mini map) is correcty dispayed. Just the picture is missing. Instead, I got a message "Cannot load image from server. Might be CORS related." on first image. 

There is no problem with older tracks, July 2020 or older.

Hints : 

My web browser opens an HTTP GET request like "https://openstreetcam.org/storage13/files/photo/2020/12/23/lth/[...]", and obtains a HTTP 301 response, Moved Permanently to "Location: https://storage13.openstreetcam.org/files/photo/2020/12/23/lth/[...]"

The HTTP request to https://storage13.openstreetcam.org/files/photo/2020/12/23/lth/[...] is denied because "CORS Missing Allows Origins".

**Comment by JiudanZheng** [comment]
@laurentriffard , may I have your user name on KartaView? Also, if you have these track numbers, it will be more helpful. Thanks.

**Comment by laurentriffard** [comment]
My user name is laurent-38,
The problem occurs on track 3333801
https://kartaview.org/details/3333801/0/track-info

**Comment by JiudanZheng** [comment]
@laurentriffard , I could see this track has been processed successfully. Some times, the time spent is beyond two days.

**Comment by laurentriffard** [comment]
Fine, but... the problem is not the processing duration.
It is : when a track is in "processing" state, pictures are not displayed because of a CORS problem.

It does still happen with new tracks, see https://openstreetcam.org/details/3340433/0/track-info for example.
(and we now know that the problem disappears when the track goes to "processed" state)

**Comment by JiudanZheng** [comment]
@laurentriffard , what browser are you using? I tried https://openstreetcam.org/details/3340433/0/track-info on chrome and it's like below:
![image](https://user-images.githubusercontent.com/54828114/103256945-11747b80-49ca-11eb-92b7-99d876d6b10c.png)

I didn't see CORS things.

**Comment by laurentriffard** [comment]
> @laurentriffard , what browser are you using? I tried https://openstreetcam.org/details/3340433/0/track-info on chrome and it's like below:
> ![image](https://user-images.githubusercontent.com/54828114/103256945-11747b80-49ca-11eb-92b7-99d876d6b10c.png)
> 
> I didn't see CORS things.

hi @JiudanZheng, I guess the error message you got is a normal one : can you really see anybody's track in "processing"state without being logged in with the track's owner account ? 

FYI, i’m using Firefox. 
When I'm logged in with my personal account, I get the CORS error message on "processing" tracks.
But after logging out, I get the "Ups! Sequence cannot be loaded... Reload or go Back" error message. I guess this one is right, because I'm not logged in and "processing" tracks are not public.

May I suggest you to record an upload a track with your own Kartaview account ?

**Comment by JiudanZheng** [comment]
I'll take a look and get back to you.

**Comment by ikealol** [comment]
Same issue here https://kartaview.org/details/3341325/0/track-info

**Comment by JiudanZheng** [comment]
I've raised this issue to our engineer team. Will get back later when the fix will be planned to do.

**Comment by ybdx** [comment]
Hi @laurentriffard, could you help to check again? we have already fixed it. If there are no problems,  can we close it first?
