### ISSUE TITLE
processing...

### ISSUE THREAD

**Issue by mvexel** [kartaview/openstreetcam.org#305]
I remember this being an issue a while ago. I uploaded a bunch of tracks more than 12 hours ago and they still all show up as 'processing'. Is this expected?

**Comment by EndlessIdea** [comment]
From the monitors, we can see almost all tracks can be processed within 12 hours, it looks good. So I will close this ticket, if you have any questions, please feel free to submit an issue, thank you!

**Comment by Lining-Grab** [comment]
From the monitors, we can see almost all tracks can be processed within 12 hours, it looks good. So I will close this ticket, if you have any questions, please feel free to submit an issue, thank you!
