### ISSUE TITLE
More failed sequences

### ISSUE THREAD

**Issue by joeybab3** [kartaview/openstreetcam.org#306]
These sequences only partially processed:
https://kartaview.org/details/3377557
https://kartaview.org/details/3377645
https://kartaview.org/details/3377889
https://kartaview.org/details/3377949
https://kartaview.org/details/3378005
https://kartaview.org/details/3378017
https://kartaview.org/details/3378057
https://kartaview.org/details/3378165

These sequences did not process at all:
https://kartaview.org/details/3382289
https://kartaview.org/details/3382957
https://kartaview.org/details/3382961
https://kartaview.org/details/3382965
https://kartaview.org/details/3382981
https://kartaview.org/details/3382985
https://kartaview.org/details/3382989

**Comment by joeybab3** [comment]
None of my sequences have processed since 2020-01-19.

**Comment by tigren** [comment]
@joeybab3 the partially processed sequences you mentioned should be processed now, we're checking the sequences not processing at all

**Comment by joeybab3** [comment]
@tigren Thanks, it seems that more than just my sequences judging by the fact that the leaderboard for monthly, weekly, and daily are once again blank.

**Comment by tigren** [comment]
@joeybab3 the 7 sequences were also processed now, sorry for the inconvenience

**Comment by tigren** [comment]
I'll close this ticket, you're welcome to reopen it if there are any other questions.
