### ISSUE TITLE
Tracks uploaded today do not show up on website

### ISSUE THREAD

**Issue by thatoneiowan** [kartaview/openstreetcam.org#307]
Earlier today I uploaded four tracks under my [account](https://openstreetcam.org/user/thatoneiowan), but as of now they do not show up in my track list, on the KV/OSC map, or even in OSM's iD editor. Usually they would show up, at least in Processing state. The tracks have since been removed automatically by the KartaView app (which I saw a different issue open on the Android section that there should be a setting for this) and I am not able to re-upload them. 

I don't remember all of them but they should have covered areas including the below OSM ways.
Sheldon Avenue Extension https://www.openstreetmap.org/way/237025592
Farm House Road https://www.openstreetmap.org/way/545499725
West Street https://www.openstreetmap.org/way/158822203
entrance to North Grand Mall https://www.openstreetmap.org/way/846579903

**Comment by joeybab3** [comment]
I think that there is a larger issue at play here, sequences I've uploaded since 2020-01-19 have not processed and the leaderboards for recent time stretches are blank.

**Comment by tigren** [comment]
@thatoneiowan sorry for that, we've re-processed your sequences, they are showing on your profile now. Please let us know if there are any missing.

@joeybab3 thanks for the reminder, leaderboard is working now.

**Comment by thatoneiowan** [comment]
> @thatoneiowan sorry for that, we've re-processed your sequences, they are showing on your profile now. Please let us know if there are any missing.

These look good, thank you!
