### ISSUE TITLE
"Ups! Authentication failed!" on every platform of KartaView.

### ISSUE THREAD

**Issue by random1910** [kartaview/openstreetcam.org#308]
It's both on the mobile app, my mobile browser and desktop browser. It gives me the message I don't know much about code but it seems an issue in the login process. I know much less about github.com, I just want to report this problem, and I suppose this is kind of the right place. I can't really help in solving it cause, I repeat, I'm not much in software. 
Hope this helps improving KartaView, I'll leave an image to better explain. Hope also to be able to login and start using kartaview.org soon. 
Ask me anything you need to solve this, I'm available at any time (unavailable-times apart).
Thanks

<img width="221" alt="Immagine 2021-02-28 122725" src="https://user-images.githubusercontent.com/79789997/109416737-5dd73a00-79c0-11eb-844b-9cfbef3649b3.png">

**Comment by Etua** [comment]
I encountered the issue as well. An email was sent so if they happen to reply faster there than here I can update you.

**Comment by random1910** [comment]
Thanks.

**Comment by Lining-Grab** [comment]
Sorry for the inconvenience! It should work now. Thanks for your patience! If there is anything wrong, please feel free to create issues,
