### ISSUE TITLE
"My Tracks" shows all tracks

### ISSUE THREAD

**Issue by joeybab3** [kartaview/openstreetcam.org#311]
On the main site, selecting "My Tracks" shows all tracks and not just those uploaded by the user

**Comment by Lining-Grab** [comment]
Hi, @joeybab3 Could you send me the specify URL? I just check my tracks in https://kartaview.org/, this issue doesn't happen.

**Comment by joeybab3** [comment]
https://kartaview.org/map/@37.1512707225056,-122.03917676926926,9z

**Comment by joeybab3** [comment]
![image](https://user-images.githubusercontent.com/2829457/110991708-d7104e80-8329-11eb-8b29-d6fe49041b8b.png)

**Comment by eserte** [comment]
Actually it seems like none of the filters work (date selection, my tracks etc.).

**Comment by joeybab3** [comment]
Seems to work fine now, closing

**Comment by eserte** [comment]
It still does not work for me. For example, if setting startDate to 2020-03-01, then there are only a few sequences visible in Berlin:
https://kartaview.org/map/@52.48154393901788,13.270133443604209,9z
It really should be thousands of sequences.
With "My Tracks Only" and without date restriction no sequence is visible.

**Comment by miruna-craciun** [comment]
@Lining-Grab - could you check @eserte 's profile? works fine on my end too

**Comment by Lining-Grab** [comment]
@eserte Hi, may I know your email? I need to check if you have any sequences around the coordinates you provide.

**Comment by eserte** [comment]
@Lining-Grab My KartaView username is also eserte and the user id seems to be 48497 --- at least the filtered tile images look like https://api.openstreetcam.org/2.0/sequence/tiles/274/167/9.png?userId=48497

**Comment by miruna-craciun** [comment]
@Lining-Grab update?

**Comment by eserte** [comment]
In the meantime, it seems that all filters work.

**Comment by zhangtiedong0912** [comment]
@eserte @joeybab3  Thanks for your feedback , i will close this issue, you can reopen this if you have any question.
