### ISSUE TITLE
Delivery Status Notification (Failure)

### ISSUE THREAD

**Issue by alantiagofelipe** [kartaview/openstreetcam.org#315]
Delivery Status Notification (Failure)

geo.kartaview@grabtaxi.com
osc-support@telenav.com

[Gmail.pdf](https://github.com/kartaview/openstreetcam.org/files/6202126/Gmail.pdf)
[Gmail.pdf](https://github.com/kartaview/openstreetcam.org/files/6202127/Gmail.pdf)

**Comment by miruna-craciun** [comment]
@alantiagofelipe - our services are running, we have received your email. Did it bounce initially?
