### ISSUE TITLE
when do deleted tracks get removed from the map?

### ISSUE THREAD

**Issue by joshinils** [kartaview/openstreetcam.org#323]
I have deleted some tracks, those still show up on https://kartaview.org/map/ with the blue line and preview images when clicking on the line.
I have deleted those at least a week ago, the preview image and line still show up.
I would like to use the map as reference as to where i need to take images and where i have already done so, an update to the map would be great in that regard.

**Comment by Lining-Grab** [comment]
@joshinils Hello Joshinils,  could you help provide the IDs of these deleted tracks or provide the link of where it's still shown ?

**Comment by joshinils** [comment]
https://kartaview.org/details/3549341/67
https://kartaview.org/details/3549229/133

or
https://kartaview.org/details/3549193/1022
at https://kartaview.org/map/@52.62371126727217,13.308486283407547,19z (the whole of Silvesterweg).

See https://www.mapillary.com/app/user/mtek?lat=52.623881900315894&lng=13.308601240452276&z=17&mapStyle=OpenStreetMap&pKey=9uBQhTlXof4KnlclspO8L8 for the mapillary sequence

I transferred my mapillary images over, which I undid. I want to keep the image quality (iPhone vs gopro) and type (backpack overhead and bike handlebar) separate. I also want to have a map as a reference where I need to take new images.

**Comment by Lining-Grab** [comment]
@joshinils  Hello, all the deleted tracks of yours are removed from the map, please check, thank you!

**Comment by joshinils** [comment]
alright, thank you. was this done manually?

**Comment by Lining-Grab** [comment]
We fixed this bug, and then wrote a script to process all the issues.
