### ISSUE TITLE
only the last photos show up on map/profile

### ISSUE THREAD

**Issue by BeJotEl** [kartaview/openstreetcam.org#325]
on may 1st/2nd 2021 I uploaded a bunch of tracks mostly direct via iOS app, later tried some of them by the upload scripts
All tracks with less than 50 photos show up correctly, all others don't.
These tracks are:
https://kartaview.org/details/3550753     17 photos, should be 67, no points counted
https://kartaview.org/details/3550729       5 photos, should be 1555, status uploading for 14 days, deleting not possible
https://kartaview.org/details/3549133     21 photos, should be 121, no points counted
https://kartaview.org/details/3549125       3 photos, should be 453, no points counted
https://kartaview.org/details/3549113      13 photos, should be 63, no points counted
https://kartaview.org/details/3549093  280 photos, should be 1630, points counted
It seems that all numbers of missing photos are multiples of 50, and the photos show up on profile/map are the last "block" of each track.

So please could you check, why the missing photos don't show up?!

For me it's not that important, that the points are counted, but the photos should show up in a short period after upload of time or at least a reason should be displayed on the profile page.

**Comment by tigren** [comment]
@BeJotEl sorry for late reply, we've reprocess the sequences except 3550729  and 3549093 
Please check other sequences

for 3550729, the uploading is not finished so we can do nothing
for 3549093, we manged to make 1180 photos processed and are still trying to process others

**Comment by BeJotEl** [comment]
@tigren Thanks for solving the issue, even sequence 3549093 seems to be complete.
Meanwhile I was able to delete sequence 3550729 and tried to upload it again, but it failed on iPhone as well as with the upload-scripts. I think I should open an issue there

**Comment by tigren** [comment]
@BeJotEl thanks, then I will close this ticket. Please create a new one if needed
