### ISSUE TITLE
not clear which ways are not covered 

### ISSUE THREAD

**Issue by joshinils** [kartaview/openstreetcam.org#328]
In comparison to [wandrer.earth](https://wandrer.earth), i do not know which ways will get painted in blue on the map after i upload a sequence taken there.
On wandrer.earth I can enable untravelled ways on my [Big Map](https://wandrer.earth/dashboard/map) (login required), I would like this for KartaView aswell.

**Comment by miruna-craciun** [comment]
Closing this as a duplicate for #327 - will follow up there w updates.
