### ISSUE TITLE
the twitter link(s) at the bottom points to the wrong account

### ISSUE THREAD

**Issue by joshinils** [kartaview/openstreetcam.org#331]
it points to https://twitter.com/openstreetcam which does not exist
not to https://twitter.com/kartaview

**Comment by miruna-craciun** [comment]
hey, @joshinils are you referring to the Twitter icon located at the bottom of kartaview.org?
That has been replaced and is now pointing to the correct page.

**Comment by joshinils** [comment]
Ah yeah, thats what i meant.

**Comment by miruna-craciun** [comment]
@joshinils make sure to clear your cache before accessing; the links have been tested and work on our end.
