### ISSUE TITLE
people and car plates are not blurred in 360 pictures

### ISSUE THREAD

**Issue by zorglubu** [kartaview/openstreetcam.org#336]
Looking at flat images, faces and number plates are correctly blurred. But with 360° pictures, if you click on "show panorama photo", they are not blurred anymore.
![image](https://user-images.githubusercontent.com/31647352/124304279-c3e8ef00-db63-11eb-9222-af4cf6ab620d.png)

**Comment by EndlessIdea** [comment]
@zorglubu Could you help provide the link?

**Comment by zorglubu** [comment]
Have a look at this picture and sequence : https://kartaview.org/details/3694345/137/track-info

**Comment by Lining-Grab** [comment]
@zorglubu Thanks for reporting this issue, this is a bug, we will solve this asap!

**Comment by EndlessIdea** [comment]
@zorglubu All 360 pictures should be blurred, please check. Thank you!

**Comment by zorglubu** [comment]
That seems OK now. Thanks.
