### ISSUE TITLE
Keep orientation of the sight with photos 360

### ISSUE THREAD

**Issue by zorglubu** [kartaview/openstreetcam.org#338]
Suggestion of enhancement.
With photos 360, I like to turn my sight 60-90° to the right or the left in order to map the shops. But every time I change the picture, I have to turn again 90° in the right direction. It would be great to keep this direction while moving from one picture to another one.
Thank you.

**Comment by zhaitianduo** [comment]
Hey good point, we developed a Web SDK and this is implemented in the SDK. Next step it to use this SDK in our website so this function works for the website.

**Comment by zorglubu** [comment]
Have you any rough idea on the delay to use it ?

**Comment by zhaitianduo** [comment]
Probably by the end of this year

**Comment by nakic** [comment]
Not critical, bu would be nice to have this available some time: inspecting a path going backwards gets really old really fast when having to rotate and zoom the view at every step...

**Comment by zhaitianduo** [comment]
https://kartaview.org/flags 
Hi @zorglubu @nakic we have the beta version released and you can use this page to enable this feature in your local  `Use streetView SDK to view photos`

**Comment by nakic** [comment]
@zhaitianduo Didn't know about the SDK view: that looks really promising, thanks!

**Comment by zorglubu** [comment]
This is absolutely great ! And it looks perfect. I will start to use it immediately. Thank you.

**Comment by zhaitianduo** [comment]
Glad to hear you love it!
Please let us know if you have any questions.

**Comment by nakic** [comment]
@zhaitianduo Is there an approximate date at which the streetview SDK will come out of beta into production and replace the current interface as the default, as this is still an issue affecting users in the meantime?
