### ISSUE TITLE
Pictures 360 are facing backward

### ISSUE THREAD

**Issue by zorglubu** [kartaview/openstreetcam.org#339]
If you look at this track : https://kartaview.org/details/3826785/309/track-info
there is a supermarket in the north of the road, but you have to look toward the south to see it (look at the green arrow on the screenshot below)

![image](https://user-images.githubusercontent.com/31647352/132088614-011af4bc-d32b-4d9c-9715-823bc96d7092.png)

Furthermore, if you click on next or previous picture, it will always face the back of the track, even if the green arrow correctly shows the front of the car.
It's quite difficult to work with these tracks (to detect road signs for example)   ;-)
Not all my tracks are like that, only some of them.
thanks.

**Comment by zhaitianduo** [comment]
Hey, @zorglubu 
looks like you are uploading the images via API？
Do you use any heading param?

**Comment by zorglubu** [comment]
Hello, I am using the script downloaded here : https://github.com/kartaview/upload-scripts
as it is. I am not really an expert, I don't know what you mean with heading param.
My OS is a linux debian. Pictures are taken with a gopro max.

Even if it's not perfect, the problem could be solved with that ? https://github.com/kartaview/openstreetcam.org/issues/338

**Comment by zhaitianduo** [comment]
![Pasted Graphic](https://user-images.githubusercontent.com/5261179/134620468-6c730b09-f38f-4820-9948-d27cfe979918.png)
I checked your images the tail of the car is in the center instead of the head of the car. So by default it's facing backward

**Comment by zorglubu** [comment]
OK, thank you. My camera is always facing front but I just realize that even in 360 mode, pictures can be taken backward.
Sorry for this ticket.

**Comment by zhaitianduo** [comment]
not a problem at all
