### ISSUE TITLE
Tracks aren't processing again

### ISSUE THREAD

**Issue by joeybab3** [kartaview/openstreetcam.org#341]
![image](https://user-images.githubusercontent.com/2829457/134282385-bbb15507-5ded-4622-a4ad-450e35f99cd9.png)
Tracks are not processing again for me. Seems like it's a site issue since there's also no data for the weekly or daily scoreboards.

**Comment by zhaitianduo** [comment]
Hey @joeybab3 We met some issues in processing and it's recovered now.

Please check

**Comment by joeybab3** [comment]
Tracks are processing again, thanks.
This track seems to have failed however, can you put it back into the queue for reprocessing: https://kartaview.org/details/3841941

**Comment by zhaitianduo** [comment]
Hey @joeybab3 there might be some delay to catch up the processing, the track looks normal to me.

Any other concerns from your side on this track?

**Comment by joeybab3** [comment]
No, I will check back in in a week if it has not processed.

**Comment by miruna-craciun** [comment]
Looks like it's published @joeybab3, please confirm on your end

**Comment by joeybab3** [comment]
> Looks like it's published @joeybab3, please confirm on your end

I can confirm that it is not processed still:
![Uploading 7961846B-BDDE-4E24-8415-2C1BE24F9D85.png…]()

**Comment by zhaitianduo** [comment]
I see, you are refering to the scoreboard, will check

**Comment by joeybab3** [comment]
When the tracks do not show up with any points they also do not process for sign detection, do not show up on the map, etc... I don't really care about the points but would like for this track to process.

**Comment by joeybab3** [comment]
I will close this as the outage has ended and the track has processed.
