### ISSUE TITLE
API to get street view images from OpenStreetCam/KartaView

### ISSUE THREAD

**Issue by vedantmodi1** [kartaview/openstreetcam.org#345]
I'm trying to find an API or even build a system to automate the retrieval of street images along with their geodata in OpenStreetCam. I went through the discussion [here](https://github.com/kartaview/openstreetcam.org/issues/284) and went through the documentation [here](http://api.openstreetcam.org/api/doc.html).
I see I require an access_token, request_token, secret_token. How do I obtain these?

There's also [this ](http://doc.kartaview.org/#operation/sequenceGetPhotoList) documentation. To retrieve photos based on the sequenceId I require a sequenceId. Where do I obtain this?

If I'm on the wrong track here, is there any other way to achieve this?

**Comment by JoshuaDietz** [comment]
As far as I can see you need the  `/nearby-tracks` or `/1.0/list/nearby-photos/` endpoints (see [here](http://api.openstreetcam.org/api/doc.html#tag-Map)) which seem to don't need any authentication.

**Comment by zhangtiedong0912** [comment]
@vedantmodi1  Has this problem been solved? l will close this issue, you can reopen this if you have any question.

**Comment by satiyam** [comment]
I am facing the same issue. It's giving me 200 status as reponse with JSON decode error.
