### ISSUE TITLE
404 Not Found error when accessing images via KV

### ISSUE THREAD

**Issue by brmonaghan** [kartaview/openstreetcam.org#348]
https://storage12.openstreetcam.org/files/photo/2019/7/26/proc/1595425_86_09fa9_1.jpg
This gives me a 404, although it shows in the viewfinder.
Can somebody please look into this?
Thanks

**Comment by brmonaghan** [comment]
Looks like this issue is still going on. @foobarna @chip-grab

**Comment by brmonaghan** [comment]
still not working! @miruna-craciun @zhaitianduo

**Comment by zhangtiedong0912** [comment]
@brmonaghan  hi i can‘t see the the photo in storage, so the photo may be deleted. let me confirm it next Mon.

**Comment by brmonaghan** [comment]
ok.

**Comment by zhangtiedong0912** [comment]
@brmonaghan  hi confrim. this image had deleted.  you can see the lth photos, [](https://storage12.openstreetcam.org/files/photo/2019/7/26/proc/1595425_86_09fa9_1.jpg) 
I'm really sorry for bringing you trouble, and I will close this issue. You can turn it back on if there's a problem
