### ISSUE TITLE
KV Not Up To Date?

### ISSUE THREAD

**Issue by brmonaghan** [kartaview/openstreetcam.org#356]
I have noticed that there is a **_LOT_** of open issues that KV needs to resolve. Multiple issues are from last year and have a long wait with support. I understand that COVID-19 has caused a lot of issues with staffing, but this is becoming a big issue. People have been waiting such as @joeybab3 and others for minor issues such as long upload times, processing issues, and especially, #349 **_NOT BEING ABLE TO DELETE SEQUENCES_**! 
@zhaitianduo @kartaview @chip-grab this needs to be resolved in order to improve customer satisfaction. I have been waiting for almost THREE MONTHS to get an answer for why there is a 404 NOT Found error when downloading old sequences from OSC (2019). I was formerly in a forum board (AARoads) that **_REQUIRES YOU_** to host the files. I don't have the time in the world for people to fix problems, I belong in a game called Road Sign UNO, which REQUIRES YOU to provide your OWN images!
Anybody feeling the same thoughts as me?

**Comment by joeybab3** [comment]
They like to go sometimes a full year without any response or update, it's been this way for the last 3 years. Ever since Telenav took over and then grab it's just been getting worse. 

Sometimes the processing server will go down and it will be down for weeks until something happens. I was able to get a response by pinging grab on Twitter asking if this project should be considered abandoned but I don't want to do that bi-yearly just to be able to contribute to a project that seems to be increasingly less interested in supporting its contributors. 

I'm considering moving to mapillary as now that they dropped support for the waylens and no longer actively maintain anything in this project it's feeling like my contributions are not needed here. 

It kind of seems like this was an experiment taken on by grab and they're realizing there's no way to make money with this much data and so they're stuck in a limbo of trying to decide how to shut it down.

**Comment by joeybab3** [comment]
I got a response via email, worth relaying here I suppose:

> Hey Joey
> 
> Sorry for replying so late. 
> 
> Really sorry we are working on an important project recently and the timeline is quite tight. Engineers do not have the capacity to check github issues.
> 
> We are glad to have you in our community and we do not want to lose you. 
> 
> I'm working on getting more resources to support our community better. Hope we will improve this soon.
> 
> Regards
> Tianduo

**Comment by zhaitianduo** [comment]
Hey, thanks for the feedback guys, team is looking into this.

**Comment by brmonaghan** [comment]
THANK YOU SO MUCH!

**Comment by brmonaghan** [comment]
Yes I can, hold on.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by brmonaghan** [comment]
Sorry about the wait. Its been taking a while
https://storage12.openstreetcam.org/files/photo/2019/9/14/proc/1962273_0_62c68_1.jpg
This file is resulting in a 404 error message.
@zhaitianduo There are MULTIPLE files from 2019 that throw this error. 
It is NOT being able to delete, it is when I click Download at the bottom right corner and it says 404.
![image](https://user-images.githubusercontent.com/71337477/155328701-b149b965-b3e0-4485-8c63-ec87daf304e0.png)

**Comment by brmonaghan** [comment]
@zhaitianduo The problem with not being able to delete is with processing tracks from 2 years ago.

**Comment by zhaitianduo** [comment]
Hey sorry @brmonaghan a bad news. We've recently cleaned up some images which might have personal information recently and during this process, we accidentally lost some images before 2020. So so sorry for the inconvinience.

but we still have a low quality version if you still find it useful to you https://storage12.openstreetcam.org/files/photo/2019/9/14/lth/1962273_0_62c68_1.jpg this is to replace the proc to lth in the url and get the low quality version

**Comment by brmonaghan** [comment]
@zhaitianduo https://kartaview.org/details/1566193
https://kartaview.org/details/1456702
https://kartaview.org/details/1455626
https://kartaview.org/details/1566873

**Comment by brmonaghan** [comment]
> Hey sorry @brmonaghan a bad news. We've recently cleaned up some images which might have personal information recently and during this process, we accidentally lost some images before 2020. So so sorry for the inconvinience.
> 
> but we still have a low quality version if you still find it useful to you https://storage12.openstreetcam.org/files/photo/2019/9/14/lth/1962273_0_62c68_1.jpg this is to replace the proc to lth in the url and get the low quality version

That's fine, I didn't even notice the files being gone.

**Comment by rebecca1009** [comment]
> @zhaitianduo https://kartaview.org/details/1566193 https://kartaview.org/details/1456702 https://kartaview.org/details/1455626 https://kartaview.org/details/1566873

Thanks for the example, those photos are fixed

**Comment by brmonaghan** [comment]
THANK YOU SO MUCH FOLKS! @zhaitianduo @zhangyu-Grab
Now closing as this issue has been resolved.
