### ISSUE TITLE
Main map purple tracks have stopped processing again

### ISSUE THREAD

**Issue by joeybab3** [kartaview/openstreetcam.org#358]
![image](https://user-images.githubusercontent.com/2829457/155220732-67d65201-7bd5-4d02-8004-18ac3f32eeb4.png)
![image](https://user-images.githubusercontent.com/2829457/155220767-096f7b25-f461-499e-a4a7-957936cffb19.png)

Tracks have finished processing, points have been assigned, but the purple tracks do not appear to have shown up on the main map.

**Comment by rebecca1009** [comment]
Please provide relevant URL to help us view

**Comment by joeybab3** [comment]
https://kartaview.org/map/@37.25342214249055,-122.05223958928786,12z
Map View

https://kartaview.org/details/4550921/0/track-info
Track

**Comment by joeybab3** [comment]
Worth noting it seems that it gave 10 points for every photo so it does not appear to have processed correctly

**Comment by joeybab3** [comment]
All uploaded tracks regardless of platform seem to be giving 10 points per image and not processing for the main map

**Comment by zhangtiedong0912** [comment]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/51616101/158123198-082a186e-2c86-4535-8123-9acd0201443e.png">

@joeybab3  fixed it, could you please check again?

**Comment by zhangtiedong0912** [comment]
i will close this issue. you can reopen this if you have any question . Thanks for your feed back.
