### ISSUE TITLE
Street Sign Detection?

### ISSUE THREAD

**Issue by lklepner** [kartaview/openstreetcam.org#365]
Hello, 

I'm looking for the latest info on street sign detection and having a hard time finding it. 

Is street sign detection enabled in the US? If not is there plans to re-enable it down the line?

Without automatic sign detection is there a way to manually tag signs?

Thanks,
Lou

**Comment by lklepner** [comment]
Quick addendum - As a new KartaView user it would be helpful if the messaging in the `Detections` tab made it clear that sign detection wasn't enabled in certain regions (or is only enabled in certain regions). I found myself trying to click the Tag Signs and Validate Detections text and wondering if I was doing things wrong. 

![image](https://user-images.githubusercontent.com/110027/157895929-0a68e465-f961-4178-84b4-060e610499f8.png)

**Comment by brmonaghan** [comment]
Unfortunately no, @foobarna said that this is NOT available anymore.
See #259 for details.

**Comment by zhangtiedong0912** [comment]
duplicate, please see [https://github.com/kartaview/openstreetcam.org/issues/259](url), i will close this.
