### ISSUE TITLE
"My tracks" filter again doesn't work

### ISSUE THREAD

**Issue by joeybab3** [kartaview/openstreetcam.org#367]
On the main site, enabling the filter for my tracks only shows all tracks regardless

**Comment by zhangtiedong0912** [comment]
Thanks for your feedback, We temporarily remove filter for service stability. and plan to recover this change this week. @joeybab3

**Comment by zhangtiedong0912** [comment]
@joeybab3  hi thanks for your feedback ,we do some optimize  and the tiles filter feature is already on，please ping me if you have question, thanks.

**Comment by joeybab3** [comment]
Got ya thanks for updating me. Is 7z the highest zoom you guys will be supporting for the tracks for now?

**Comment by joeybab3** [comment]
@zhangtiedong0912 Also on zoom level 8 "my tracks" shows all tracks but the other levels work as expected

**Comment by zhangtiedong0912** [comment]
@joeybab3  yes, filter started to work after 9.
