### ISSUE TITLE
Kartaview photos are not displayed anymore on OSM ID Editor

### ISSUE THREAD

**Issue by RobinGoix** [kartaview/openstreetcam.org#368]
Hi,

Kartaview pictures are not visible anymore on OSM Id-Editor. 

I raised this issue on iD github platform (https://github.com/openstreetmap/iD/issues/9075#issue-1202904122), and they answered that the issue could be from your server settings.

Are you able to fix this?

Thank you for your help!

**Comment by joeybab3** [comment]
![image](https://user-images.githubusercontent.com/2829457/163699870-61976f09-5a00-4800-98c7-4ca4df8ae731.png)

**Comment by zhaitianduo** [comment]
Hey thanks for the report, there are some infrastructure changes recently, the team is fixing this.

**Comment by zhaitianduo** [comment]
Hey this should be fixed already, please check, thanks

**Comment by joeybab3** [comment]
Yes it works again
![image](https://user-images.githubusercontent.com/2829457/164581375-08db49dd-88bd-4742-a06a-159245f666a7.png)

**Comment by RobinGoix** [comment]
Thank you!
