### ISSUE TITLE
Edit user name

### ISSUE THREAD

**Issue by razzeee** [kartaview/openstreetcam.org#376]
It would be nice to be able to change the user name from the Website. As I setup my account via google and don't want to show up with that name.

**Comment by zhangtiedong0912** [comment]
thanks for your feedback, will support this in the future. i can help you you change name if you need

**Comment by razzeee** [comment]
Thank you, I'm already in contact with the support

**Comment by miruna-craciun** [comment]
@razzeee - is this your current username - https://kartaview.org/user/kolja-lampe?
