### ISSUE TITLE
Processing tracks are taking longer than expected?

### ISSUE THREAD

**Issue by ghost** [kartaview/openstreetcam.org#385]
Hello @chip-grab @zhaitianduo @miruna-craciun
I am seeing that my tracks are processing at a MUCH slower rate than expected.
![image](https://user-images.githubusercontent.com/71337477/209866681-093996e8-10c4-441d-b17c-a235933d086f.png)
Is there a problem with the KV server or is there something I need to do?
@joeybab3 are you having the same problems?

**Comment by zhaitianduo** [comment]
Hey @brmonaghan Happy new year! Do you have a link for that?
