### ISSUE TITLE
Website Interface Does Not Remove Map Route Lines.

### ISSUE THREAD

**Issue by drkludge** [kartaview/openstreetcam.org#71]
As per [issue #5 of the uploader program, ](https://github.com/openstreetview/uploader/issues/5#issuecomment-242397571) I had to remove 100 plus tracks of uploaded images. The images were removed.  The tracks lines on the main map are still visible were the deleted images used to be. The uploader issue was resolved.  I have uploaded one track so far.  All that should be shown on the map are the 315 images  of sequence 14860.  Would you please look into this issue?  I think there is a problem because the images were deleted 12 hours ago.
![image](https://cloud.githubusercontent.com/assets/1669057/18007850/8f37d95c-6b5a-11e6-8c39-ebc380614ae1.png)

Here's a list of sequences that should be deleted from the map route lines.  The list excludes my two good uploads at this point.  The list was developed from the exif uploader's sequence_file.txt files.
14314
14320
14321
14324
14325
14326
14329
14330
14331
14332
14333
14334
14335
14336
14337
14338
14339
14340
14341
14343
14344
14345
14346
14347
14348
14350
14351
14352
14353
14354
14355
14357
14358
14359
14360
14362
14363
14364
14365
14368
14369
14370
14371
14373
14375
14376
14378
14384
14392
14395
14405
14406
14407
14410
14411
14413
14414
14415
14417
14418
14420
14421
14423
14425
14427
14429
14430
14431
14432
14433
14434
14437
14443
14444
14445
14448
14452
14453
14454
14456
14457
14458
14459
14460
14461
14462
14463
14464
14465
14466
14467
14468
14469
14470
14471
14472
14473
14474
14476
14591
14593
14596
14597

**Comment by joshinils** [comment]
seems like this is the case for still. i deleted a bunch of sequences a few days ago, but those still show up on the map

**Comment by miruna-craciun** [comment]
Solved - ref #314
