### ISSUE TITLE
Logging in generates Bad API req

### ISSUE THREAD

**Issue by martijnv-telenav** [kartaview/openstreetcam.org#96]
Not always but I get this from time to time:

![screenshot 2017-01-04 09 43 38](https://cloud.githubusercontent.com/assets/15021381/21650628/d24942b6-d262-11e6-8f94-0f9cb41fbc16.png)

**Comment by mirunac-telenav** [comment]
@martijnv-telenav - is this still valid?

**Comment by mvexel** [comment]
not checked recently but feel free to close, this API will be deprecated soon anyway.

**Comment by james2432** [comment]
@mvexel what is replacing the api?
